version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: hopscotch-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-api
      - orders-api
      - products-api
    networks:
      - hopscotch-network

  orders-api:
    build: ./orders
    container_name: hopscotch-orders-api
    environment:
      - HOST=hopscotch-postgres
      - USER=postgres
      - PASSWORD=yourpassword
      - DATABASE=hopscotch_db
      - DATABASE_PORT=5432
    depends_on:
      - postgres
    networks:
      - hopscotch-network

  products-api:
    build: ./products
    container_name: hopscotch-products-api
    environment:
      - HOST=hopscotch-postgres
      - USER=postgres
      - PASSWORD=yourpassword
      - DATABASE=hopscotch_db
      - DATABASE_PORT=5432
    depends_on:
      - postgres
    networks:
      - hopscotch-network

  user-api:
    build: ./user
    container_name: hopscotch-user-api
    environment:
      - HOST=hopscotch-postgres
      - USER=postgres
      - PASSWORD=yourpassword
      - DATABASE=hopscotch_db
      - DATABASE_PORT=5432
    depends_on:
      - postgres
    networks:
      - hopscotch-network

  postgres:
    image: postgres:14
    container_name: hopscotch-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: hopscotch_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - hopscotch-network

volumes:
  postgres-data:

networks:
  hopscotch-network:
    driver: bridge
